_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: can34_eval
  offset: 1836
  eval_length: 336
  prediction_lengths: [48]
  context_lengths: [720, 1440]
  patch_sizes: [16, 32, 64]