_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: ind78-3month-1hr_eval
  offset: 720
  eval_length: 36
  prediction_lengths: [4]
  context_lengths: [720, 360]
  patch_sizes: [32, 64]