_target_: uni2ts.model.moirai.MoiraiForecast
module:
  _target_: uni2ts.model.moirai.MoiraiModule.from_pretrained
  pretrained_model_name_or_path: juncliu/moirai_1.1_R_small_tsmixup_10m
num_samples: 100
patch_size: ???
context_length: ???