_target_: uni2ts.model.moirai.MoiraiForecast
module:
  _target_: uni2ts.model.moirai.MoiraiModule.from_pretrained
  pretrained_model_name_or_path: juncliu/moirai-1.1-R-small_lotsa_v1_univar
num_samples: 100
patch_size: ???
context_length: ???