_target_: uni2ts.data.builder.ConcatDatasetBuilder
_convert_: all
_args_:
  - _target_: uni2ts.data.builder.ConcatDatasetBuilder
    _args_:
      _target_: uni2ts.data.builder.simple.generate_eval_builders
      dataset: ETTh1_eval
      offset: 11520
      eval_length: 2880
      prediction_lengths: [96, 192, 336, 720]
      context_lengths: [1000, 2000, 3000, 4000, 5000]
      patch_sizes: [32, 64]
#  - _target_: uni2ts.data.builder.ConcatDatasetBuilder
#    _args_:
#      _target_: uni2ts.data.builder.simple.generate_eval_builders
#      dataset: ind82_eval
#      offset: 1836
#      eval_length: 336
#      prediction_lengths: [48]
#      context_lengths: [720, 1440]
#      patch_sizes: [16, 32, 64]
#  - _target_: uni2ts.data.builder.ConcatDatasetBuilder
#    _args_:
#      _target_: uni2ts.data.builder.simple.generate_eval_builders
#      dataset: deu38_eval
#      offset: 1836
#      eval_length: 336
#      prediction_lengths: [ 48 ]
#      context_lengths: [ 720, 1440 ]
#      patch_sizes: [ 16, 32, 64 ]



#- _target_: uni2ts.data.builder.ConcatDatasetBuilder
#  _args_:
#    _target_: uni2ts.data.builder.simple.generate_eval_builders
#    dataset: ETTh1_eval
#    offset: 11520
#    eval_length: 2880
#    prediction_lengths: [96, 192, 336, 720]
#    context_lengths: [1000, 2000, 3000, 4000, 5000]
#    patch_sizes: [32, 64]